# Betting Website Configuration

site_name: "Betting Game Hub"
author: "Your Name"
description: "A modern betting website featuring games like Crossfire, Dota 2, Mobile Legends with room creation, chat, credit system, deposit & withdraw features."
version: "1.0.0"

theme:
  name: "modern-light"
  primary_color: "#4F46E5"        # Indigo-600
  secondary_color: "#3B82F6"      # Blue-500
  accent_color: "#F59E0B"         # Amber-500
  background_color: "#F9FAFB"     # Gray-50
  card_background: "#FFFFFF"      # White
  text_primary: "#111827"         # Gray-900
  text_secondary: "#6B7280"       # Gray-500
  font_family: "'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  border_radius: "8px"
  box_shadow: "0 4px 12px rgba(0, 0, 0, 0.1)"

features:
  - User registration & login with email verification
  - Credits system with deposit & withdrawal (admin approval)
  - Game rooms with unique names and bet amounts
  - Team selection (Red & Blue)
  - Real-time chat in rooms
  - Admin panel for managing deposits and withdrawals

website: "https://arch1play.github.io/alz-gaming.github.io/"
license: "MIT"

