# Betting Website Configuration

site_name: "Betting Game Hub"
author: "Your Name"
description: "A betting website featuring games like Crossfire, Dota 2, Mobile Legends with room creation, chat, credit system, deposit & withdraw features."
version: "1.0.0"

theme:
  name: "dark-mode"
  primary_color: "#1e1e2f"
  secondary_color: "#3e3e5e"
  accent_color: "#ff4d4d"
  font_family: "Segoe UI, Tahoma, Geneva, Verdana, sans-serif"
  background_color: "#12121f"
  text_color: "#ffffff"

features:
  - User registration & login with email verification
  - Credits system with deposit & withdrawal (admin approval)
  - Game rooms with unique names and bet amounts
  - Team selection (Red & Blue)
  - Real-time chat in rooms
  - Admin panel for managing deposits and withdrawals

repository: "https://github.com/yourusername/betting-game-website"
license: "MIT"
